### ISSUE TITLE
[Feature request] Add brightess control

### ISSUE THREAD

**Issue by werdahias** [ErikReider/SwayOSD#1]
Thank you for making this software. Maybe more actions/symbols such as brightness and mute control (maybe play/pause) would make it even better.

**Comment by ErikReider** [comment]
Mute is already added but I'm working on the others :)

**Comment by werdahias** [comment]
Awesome, thanks :)

**Comment by ad-laurentius** [comment]
Just started using SwayOSD and it just works and looks amazing! Adding brightness would just be the cherry in the cake!

**Comment by ErikReider** [comment]
Fixed by #4
