### ISSUE TITLE
Diffrent sized outputs break swayosd layout

### ISSUE THREAD

**Issue by chron-isch** [ErikReider/SwayOSD#10]
Hi, thanks you for the work on this, it's been extremly usefull!

While it works, when you start `swayosd` while having both outputs connected/active, the moment you disable and re-enable an output, it breaks the `swayosd` layout and it starts appearing all over the screen.

Right after starting `swayosd` with both outputs active:
![20230427_11h25m45s_grim](https://user-images.githubusercontent.com/1332352/234820905-1c56e0fb-c877-4c8f-bac2-158ef0018088.png)

After disabling/re-enabling one output:
![20230427_11h24m08s_grim](https://user-images.githubusercontent.com/1332352/234821032-9aae7837-d3ca-4d0b-81e2-e8bfe9893503.png)

**Comment by ErikReider** [comment]
Thanks! I've also experienced this but I've never found a way of reproducing it...

**Comment by ErikReider** [comment]
Should be fixed now :)

**Comment by chron-isch** [comment]
I can confirm that it works. Thanks! :)
