### ISSUE TITLE
How to make the window layer pass the mouse events through?

### ISSUE THREAD

**Issue by KorigamiK** [ErikReider/SwayOSD#110]
I would like to make the window non intractable via the mouse when it is visible. Is this possible on wayland?

**Comment by Ferdi265** [comment]
According to the [wlr-layer-shell docs](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_keyboard_interactivity) it's possible to not receive input events by setting the [input region](https://wayland.app/protocols/wayland#wl_surface:request:set_input_region) of the surface to an empty region.

I'm not sure though if GTK and gtk3-layer-shell/gtk4-layer-shell implement a way to override the input region though.

**Comment by KorigamiK** [comment]
Hi, yeah I just implemented something similar in my app as well which works as expected 

https://github.com/KorigamiK/focusclock/blob/main/main.cc#L77-L79

**Comment by Ferdi265** [comment]
> Hi, yeah I just implemented something similar in my app as well which works as expected
> 
> https://github.com/KorigamiK/focusclock/blob/main/main.cc#L77-L79

Great! Sounds easy enough to implement.

@ErikReider, would you want this to be toggle-able or do we want this to be on all the time? I personally don't see where the OSD would need keyboard or mouse focus.

**Comment by Ferdi265** [comment]
For mouse events I also found [gdk4.Surface.set_input_region()](https://docs.gtk.org/gdk4/method.Surface.set_input_region.html) , which should be able to set the mouse input region to empty, if that is necessary.

**Comment by ErikReider** [comment]
> For mouse events I also found [gdk4.Surface.set_input_region()](https://docs.gtk.org/gdk4/method.Surface.set_input_region.html) , which should be able to set the mouse input region to empty, if that is necessary.
> 
> That function goes through `wl_surface.set_input_region()` on GdkWayland.

Yeah, this is the way to do it for mouse input. The keyboard input should already be set to non_interactive if I remember correctly
