### ISSUE TITLE
swayosd --input-volume mute-toggle mutes output

### ISSUE THREAD

**Issue by bartlibert** [ErikReider/SwayOSD#14]
When I execute `swayosd --input-volume mute-toggle` to toggle my microphone, I get the regular "microphone volume" popup (volume at 100%), but instead of the microphone being toggled, the output volume gets muted. I'm using swayosd 5c2176a, installed from Arch AUR. Running `swayosd --input-volume mute-toggle` again does nothing (so it does not unmute the output volume)

Steps to reproduce:
1. Make sure input and output volume are unmuted (e.g. via pavucontrol)
2. Execute `swayosd --input-volume mute-toggle`
3. Observe 'mic 100%' popup
4. Observe output volume is muted

**Comment by kescherCode** [comment]
For me, `swayosd --input-volume mute-toggle` does the same as `swayosd --input-volume lower`

**Comment by matt1432** [comment]
> For me, `swayosd --input-volume mute-toggle` does the same as `swayosd --input-volume lower`

Same here
