### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by jgmdev** [ErikReider/SwayOSD#2]
Just letting a note to notify that I added a package to the ArchLinux User Repository https://aur.archlinux.org/packages/swayosd-git

**Comment by ErikReider** [comment]
Cool, thanks! Do you want it linked in the README?

**Comment by jgmdev** [comment]
Feel free to add it if you want, by the way, nice project 👍

**Comment by ErikReider** [comment]
> by the way, nice project +1 using it on wayfire.

Thanks! :)

Hopefully the CAPSLOCK feature works better there than on Sway. Sway's a bit weird and only registers the hotkey if only the capslock key is pressed... I'll have to figure something out
