### ISSUE TITLE
`swayosd-libinput-backend` is using 100% of one CPU core

### ISSUE THREAD

**Issue by otaj** [ErikReider/SwayOSD#26]
Hi, thank you for the awesome project! I like the aesthetics a lot more than avízo, which I was using until now and wanted to make a switch, however it seems, that when I start and enable the `swayosd-libinput-backend.service`, the backend is running at 100% of one core.

I don't have any logs for you since it doesn't output anything. If there's a way, how to collect them to be more helpful, please, let me know.

I'm running on Arch, however not using AUR package, which is currently outdated, but a custom one, which uses `meson` and therefore installs everything (`udev`, `polkit` rules, service files, etc.)

Thank you!

**Comment by ErikReider** [comment]
Good catch! Fixing :)

**Comment by ErikReider** [comment]
Closed by: [bfb49f0](https://github.com/ErikReider/SwayOSD/commit/bfb49f0e24db83869bafb5f696fba71dbdecd0dc)

**Comment by otaj** [comment]
Oh wow, that was super fast, thanks! I can confirm, now it works.
