### ISSUE TITLE
Caps lock always show as on

### ISSUE THREAD

**Issue by cristomc** [ErikReider/SwayOSD#3]
Hi, I just intalled it with Hyprland, but I noticed that after binding it to the caps lock key, the message is always "Caps Lock On".

My binding in the hyprland,conf

`bind = , Caps_Lock, exec, swayosd --caps-lock`

Maybe we need a toggle parameter for it?

Good job btw, I'm setting it as a needed package for my custom iso :)

**Comment by ErikReider** [comment]
Does the LED show up in `/sys/class/`? Mine shows up as `/sys/class/leds/input19::capslock/brightness`

**Comment by cristomc** [comment]
Yeah, I have it
`ls /sys/class/leds | grep capslock                                                02/17/2023 11:49:03
│  2 │ /sys/class/leds/input25::capslock       │ symlink │  0 B │ 4 hours ago │
│  7 │ /sys/class/leds/input27::capslock       │ symlink │  0 B │ 4 hours ago │
│ 12 │ /sys/class/leds/input31::capslock       │ symlink │  0 B │ 4 hours ago │
│ 17 │ /sys/class/leds/input32::capslock       │ symlink │  0 B │ 4 hours ago │
│ 22 │ /sys/class/leds/input33::capslock       │ symlink │  0 B │ 4 hours ago │
│ 27 │ /sys/class/leds/input4::capslock        │ symlink │  0 B │ 4 hours ago │`

**Comment by ErikReider** [comment]
Which one is used by your kb? Do you have 6 keyboards connected? 😄

What SwayOSD does is that it checks for the first path that contains "capslock"

**Comment by cristomc** [comment]
TBH I don't know why looks like I have 6 keyboards :confused: 

I have a laptop and a keyboard (xtrfy, also has a bundle of leds... maybe that's why it look I have many), so maybe it needs to do a safe "check" that is really checking a keyboard caps led.

As I can see in the code, the  get_caps_lock_state() will execute for each element it finds with the capslock. It may be possible that one of the "undesired" leds of the external keyboard is the guilty  of being read as cap key...

**Comment by ErikReider** [comment]
I'm adding a way to specify which LED to use. Would that work?

**Comment by Animaly0** [comment]
I'm actually also on Hyprland and I kinda have the same problem but with only one keyboard.
I do have sometime "Caps Lock Off" that shows up but it's hardly reproducible, sometime waiting a few seconds is enough, sometime not :/

```
⋊> ~ ls /sys/class/leds/                                              16:10:21
asus::kbd_backlight@      input3::capslock@  input3::scrolllock@
asus-wireless::airplane@  input3::numlock@   phy0-led@
⋊> ~ cat /sys/class/leds/input3::capslock/brightness                  16:11:29 
0
⋊> ~ cat /sys/class/leds/input3::capslock/brightness                  16:11:47
1
```

**Comment by ErikReider** [comment]
Should now be fixed. Example: `--caps-lock-led input19::capslock`
