### ISSUE TITLE
Configfile? 

### ISSUE THREAD

**Issue by RoccoRakete** [ErikReider/SwayOSD#36]
Is there any config file to configure it's look? Or do I miss something?

**Comment by Jonher937** [comment]
It will try to load a user provided style.css on startup:
https://github.com/ErikReider/SwayOSD/blob/1add33d9ca7d9fa9be3cea39fd300e34ba3417c5/src/main.rs#L54-L66

Path is taken from here:
https://github.com/ErikReider/SwayOSD/blob/1add33d9ca7d9fa9be3cea39fd300e34ba3417c5/src/utils.rs#L374-L380

Which would probably equate to `~/.config/swayosd/style.css`

**Comment by RoccoRakete** [comment]
Ahh perfect! This looks great.

**Comment by ErikReider** [comment]
Oh! I misread the issue. You were looking for a CSS file to customize! Closing due to it already being added :)

**Comment by scientiac** [comment]
@ErikReider,  How do I  decrease the Icon size via css?

**Comment by Haraven** [comment]
A wiki for how to customize the various OSD elements would really help.

Currently, I'm stuck trying to figure out how to customize the color and size of the volume progress bar.

**Comment by mesteryui** [comment]
Yes more documentation would be useful

**Comment by malikwirin** [comment]
> Yes more documentation would be useful

yess, I need to know how to edit the text of the caps lock thing

**Comment by nxs-neo** [comment]
Is there a way to add a border or change the radius of the window itself?

**Comment by SMOON1442** [comment]
> Is there a way to add a border or change the radius of the window itself?

you can add this example to your `~/.config/swayosd/style.css`  file
```
window#osd {
  border-radius: 20px;
  border: 2px solid #yourcolor;
...
}
```

**Comment by Waito2** [comment]
> Is there a way to change the position of swayosd window?

I'm not a native English speaker, sorry. (Google translate).
You need to add a margin to the left, top, or bottom, depending on your preference in your `~/.config/swayosd/style.css`
like this:
```
window#osd {
    margin-bottom: 600px; 
    margin-left: 500px;
    border-radius: 12px;
    border: none;
    background: #2b3339;
    padding: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.5);
    . . .
}
```
I have no idea how to move it to the left. If you figure out how to move it to the left, please let me know.

**Comment by ErfanRasti** [comment]
I've found this:
```toml
[server]
top_margin = 0.14
```
You can use this for vertical alignment.
For horizontal alignment your method is nice. Thanks!

I've configured `swayosd` like this:

<img width="386" height="103" alt="Image" src="https://github.com/user-attachments/assets/90a27475-bfe7-48de-bcbb-3f59317e9ac3" />

and [here](https://github.com/ErfanRasti/dotfiles/tree/main/swayosd/.config/swayosd) is my dotfiles. It is combined with [matugen](https://github.com/InioX/matugen).

**Comment by thesupertechie** [comment]
Can the app use the system GTK theme?

**Comment by ErikReider** [comment]
> Can the app use the system GTK theme?

It already does :)
