### ISSUE TITLE
Feature request: Raise and lower by a percentage

### ISSUE THREAD

**Issue by augustebaum** [ErikReider/SwayOSD#37]
Hi,

Great work on SwayOSD!

Both `pactl` and `brightnessctl` offer the possibility to change volume and brightness by a percentage, which is supposed to be [closer to how humans perceive changes](https://medium.com/zattoo_tech/logarithmic-volume-control-bd89cc1f2135).

Would you consider making this possible with SwayOSD also? It would also help with compatibility I guess.

**Comment by trollLemon** [comment]
I think this would be a good feature. I want to contribute to this repository, and I am interesting in working on a pull request for this feature if the repository owner approves.

Considering the current implementation of the --brightness and --output-volume functionality, which only accepts integers, would it be appropriate to introduce new commands specifically for percentage values? From my understanding, the existing code base handles flag and argument parsing for brightness and volume based on an expected u8 value. Implementing percentage support to the current arguments might require rewriting a lot of code to expect percentage values.

I'm curious to see what others think.

**Comment by ErikReider** [comment]
I'd prefer having this as a config option when I get that going :)
