### ISSUE TITLE
SwayOSD command waiting for libinput backend when not running

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayOSD#40]
Small question regarding this change, is there a way to disable trying to access the listener when using `swayosd`?
I don't have the listener running (I just want to use the keybindings in the config), but when I run any `swayosd` command it now hangs waiting for the listener
```
$ swayosd --brightness raise
SwayOSD LibInput Backend isn't available, waiting...
```

P.S. Brightness change works fine for me, can't reproduce the issue as described in #12

_Originally posted by @simonvanderveldt in https://github.com/ErikReider/SwayOSD/issues/23#issuecomment-1666936612_

**Comment by ErikReider** [comment]
@simonvanderveldt moved your question into a new issue :)

**Comment by simonvanderveldt** [comment]
@ErikReider Thanks for the quick reply, apologies for the delay.
Seems like you're right, I didn't have a separate running `swayosd` instance. I didn't really get from the readme (https://github.com/ErikReider/SwayOSD#swayosd-frontend) that this was necessary. Might be clearer to explicitly mention that a instance of swayosd should be run like a daemon?

I still get the
```
SwayOSD LibInput Backend isn't available, waiting...
```
message when running a command even with swayosd running as a daemon, but the command gets executed as expected now. Thanks!

**Comment by ErikReider** [comment]
Good! I'll be closing this then. I'll be pushing a PR that might cause some breakage which separates the frontend into server + client executables to make this less confusing #43
