### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by ErikReider** [ErikReider/SwayOSD#42]

**Comment by simonvanderveldt** [comment]
If you want to skip the file-parsing things like disable the notification for caps lock could also be a command-line argument

**Comment by ErikReider** [comment]
> If you want to skip the file-parsing things like disable the notification for caps lock could also be a command-line argument

I'm feeling like there are too many args that would be better suited as config options like the top margin and these kinds of options. Don't want it to get bloated :)
