### ISSUE TITLE
Cannot build with `--buildtype=release` 

### ISSUE THREAD

**Issue by otaj** [ErikReider/SwayOSD#47]
Hi, due to `#![feature(if_let_guard)]` line, the project cannot be built in release buildtype with an error `error[E0554]: ``#![feature]`` may not be used on the stable release channel`.

I stumbled upon this when trying to update the package through AUR. Yes, I agree it is more of an AUR issue, than swayosd issue, however I'd argue that expecting release channel to work should not be the responsibility of the packager, but of the maintainer.

Thank you for all the work!

**Comment by ErikReider** [comment]
Fixed by: ed835ab3

**Comment by otaj** [comment]
Awesome! Thanks!
