### ISSUE TITLE
Is raise and lower fixed?

### ISSUE THREAD

**Issue by hoopengo** [ErikReider/SwayOSD#5]
I want to change it equal 2

**Comment by ErikReider** [comment]
Are you referring to the volume steps?

**Comment by hoopengo** [comment]
> Are you referring to the volume steps?

yeah, and brightness

**Comment by ErikReider** [comment]
I'll look into it when I have time :)

**Comment by hoopengo** [comment]
> I'll look into it when I have time :)

thanks a lot. can you please recommend me osd that have this feature?

**Comment by ErikReider** [comment]
I'm cooking something up rn. Will open a PR in a bit :)

**Comment by ErikReider** [comment]
Fixed :)

**Comment by hoopengo** [comment]
thanks)
