### ISSUE TITLE
Fedora Copr

### ISSUE THREAD

**Issue by RichardFevrier** [ErikReider/SwayOSD#52]
Hi 👋
Would you mind to make a copr for this project? I'm already using your other one for `SwayNotificationCenter` which is very useful (they could even be under the same one I think).

Thanks for all your work 🙂

**Comment by ErikReider** [comment]
I'll probably get to this when I have more time on my hands

**Comment by Polyvyanyy** [comment]
https://copr.fedorainfracloud.org/coprs/polyvyanyy/SwayOSD/

**Comment by ErikReider** [comment]
> [copr.fedorainfracloud.org/coprs/polyvyanyy/SwayOSD](https://copr.fedorainfracloud.org/coprs/polyvyanyy/SwayOSD/)

Thanks for picking up my slack! :)
