### ISSUE TITLE
Brightness feature didn't work

### ISSUE THREAD

**Issue by chenelias** [ErikReider/SwayOSD#55]
I add a .rules file to `/etc/udev/rules.d/`:
```
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
```

and run the command `sudo usermod -a -G video $USER`
but it didn't work as I expected.

**Comment by chenelias** [comment]
After I try this on nixos, it didn't work.

**Comment by leon-erd** [comment]
Maybe this helps: [#12](https://github.com/ErikReider/SwayOSD/issues/12#issuecomment-1950581102)

**Comment by ErikReider** [comment]
Is this still an issue? Closing in the meantime.
