### ISSUE TITLE
Less intrusive brightness control (and other?)

### ISSUE THREAD

**Issue by emilyyyylime** [ErikReider/SwayOSD#56]
I, for one, am less fond of messing with groups and udev rules to change brightness when I already have other utilities that can do that without such intrusions (e.g. `brightnessctl`). I would appreciate a design that relies less on lower-level APIs and/or just having options similar to the ones for caps lock on the 'continuous' inputs as well (rather than the hack of setting to +0), so I can compose my preferred control methods appropriately.

**Comment by emilyyyylime** [comment]
Actually +0 seemingly doesn't work for any brightness value other than 100%

**Comment by AlecsFerra** [comment]
+1
