### ISSUE TITLE
light background when the gtk theme is light

### ISSUE THREAD

**Issue by p00f** [ErikReider/SwayOSD#58]
I switch to light theme using
```
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
```

Then the OSD bar changes to dark, but the background doesn't change to light, making it unreadable:
![image](https://github.com/ErikReider/SwayOSD/assets/36493671/dd830eb6-1ff8-4d89-81ed-f2a1cafd23e9)

**Comment by ErikReider** [comment]
Can't seem to reproduce, maybe there's an update to the Adwaita theme?

**Comment by chron-isch** [comment]
I've had the same/similar issue, using a light theme, but SwayOSD insists on using a white background, making it almost unreadable. 

I just use my own style.css to work around the issue, forcing SwayOSD to use fixed colors.

**Comment by p00f** [comment]
this has been fixed, see the linked pr
