### ISSUE TITLE
Missing icon for full input volume

### ISSUE THREAD

**Issue by emilyyyylime** [ErikReider/SwayOSD#61]
When I run a SwayOSD command that finishes with the input unmuted and on full volume it appears there is a missing icon image used rather than the icon used for volumes just below full:
![Screenshot of said icon](https://github.com/ErikReider/SwayOSD/assets/40892795/0eca52c4-3f25-4410-ab43-1c132f24a84b)

**Comment by ErikReider** [comment]
Could you provide an example that I can run to reproduce this?

**Comment by emilyyyylime** [comment]
I can't actually replicate it anymore, but when it was a problem it was any command that would show the mic icon in that state
