### ISSUE TITLE
libinput backend failes to start due to security policies in the configuration file

### ISSUE THREAD

**Issue by kfirufk** [ErikReider/SwayOSD#65]
Hi
I'm on gentoo linux ~amd64
with geforce gtx 3060
latest nvidia drivers with drm and kernel-open
with wayland and hyprland 0.8.0
dbus version 1.15.8

i use latest version from git,
when i try to run wayosd-libinput-backend manually i get:

```Error: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.80" is not allowed to own the service "org.erikreider.swayosd" due to security policies in the configuration file```

i'm really not familiar with dbus so maybe my angel is completely wrong, but i tried to add the file `/etc/dbus-1/session.d/swayosd.conf` and to add to it `<allow send_destination="org.erikreider.swayosd" />` but it didn't make any difference.

**Comment by ErikReider** [comment]
Enable the system systemd service: `systemctl enable --now swayosd-libinput-backend.service`

**Comment by kfirufk** [comment]
starting the service failed thats why i checked what the service runs and i ran it manually. using pkexec doesn't change anything:

```
Error: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.154" is not allowed to own the service "org.erikreider.swayosd" due to security policies in the configuration file
```

**Comment by kfirufk** [comment]
i ran `ninja install`, just ran again, this is the output:

```
 # ninja install
[0/4] Generating src/cargo-build: swayosd-server with a custom command
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
[1/4] Generating src/cargo-build: swayosd-client with a custom command
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
[2/4] Generating src/cargo-build: sw...binput-backend with a custom command
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
[3/4] Installing files.
Installing src/swayosd-server to /usr/local/bin
Installing src/swayosd-client to /usr/local/bin
Installing src/swayosd-libinput-backend to /usr/local/bin
Installing /home/ufk/src/SwayOSD/data/../LICENSE to /usr/local/share/licenses/swayosd
Installing /home/ufk/src/SwayOSD/data/udev/99-swayosd.rules to /usr/local/lib64/udev/rules.d
Installing /home/ufk/src/SwayOSD/data/dbus/org.erikreider.swayosd.conf to /usr/local/share/dbus-1/system.d
Installing /home/ufk/src/SwayOSD/data/polkit/rules/org.erikreider.swayosd.rules to /usr/local/share/polkit-1/rules.d
Installing /home/ufk/src/SwayOSD/build/data/org.erikreider.swayosd.policy to /usr/local/share/polkit-1/actions
Installing /home/ufk/src/SwayOSD/build/data/org.erikreider.swayosd.service to /usr/local/share/dbus-1/system-services
Installing /home/ufk/src/SwayOSD/build/data/swayosd-libinput-backend.service to /lib/systemd/system
```

**Comment by ErikReider** [comment]
You'll probably need to compile with `--prefix /usr`

**Comment by kfirufk** [comment]
thanks :)
