### ISSUE TITLE
caps-lock osd not respecting capslock swap

### ISSUE THREAD

**Issue by Doomer-Cat** [ErikReider/SwayOSD#70]
I use capslock:swapescape a lot 

The osd activates when i hit escape (actual key: capslock)
and doesn't when i hit capslock (actual key: escape)
```sh
input "type:keyboard" xkb_options caps:swapescape
```

**Comment by Doomer-Cat** [comment]
Workaround is not using the backend like mentioned in the readme.md but remaining issue is the osd being activated by escape key in this case 

PS: i have a device without capslock led

**Comment by darkshitllord** [comment]
I have the same issue, im running hyprland though, i had to set this in my config file 
`bind = ,Caps_lock, exec, sleep 0.1 && swayosd-client --caps-lock`
In my case for example, in order for the caps lock on/off to appear on screen only when i press caps lock (actual key escape), i have to run swayosd-server and then do systemctl stop swayosd-server(not the actual name of the process, something like swaysod backend service).

**Comment by ablizno** [comment]
remapping capslock with a tool like `keyd` instead of through the sway config fixes this as it works on a system level.

**Comment by ErikReider** [comment]
The server is using libinput as the notifier, so there's not much that I can do…

**Comment by IamJomm** [comment]
> The server is using libinput as the notifier, so there's not much that I can do…

cant you add an option that would display caps lock status on esc press instead of caps lock?
