### ISSUE TITLE
Create version tag.

### ISSUE THREAD

**Issue by mike7d7** [ErikReider/SwayOSD#72]
Hello, I'm currently working on packaging this project for Void Linux, but it's a [requirement](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements) to use a version tag. 

Thanks for all your work.

**Comment by jabuxas** [comment]
yup would be nice

**Comment by ErikReider** [comment]
Waiting for a few PRs to get merged :)

**Comment by werdahias** [comment]
@ErikReider this would also ease distribution in Debian. Right now we ship the git head but version tags would be great

**Comment by ErikReider** [comment]
https://github.com/ErikReider/SwayOSD/releases/tag/v0.1.0
