### ISSUE TITLE
never ending Connecting to the SwayOSD LibInput Backend

### ISSUE THREAD

**Issue by Boris00035** [ErikReider/SwayOSD#74]
Hello! I was trying to use swayOSD on my machine, but couldnt get it to work. I have started the libinput backend via systemd, but when I run swayosd-server, it says that it is connecting to the swayosd libinput backend, but it never seems to connect. It just hangs and does nothing. 

I am running Hyprland, so maybe that has something to do with it? I found this project in this list [awesome-hyprland](https://github.com/hyprland-community/awesome-hyprland) 

I installed with the AUR package swayosd-git.

systemctl status swayosd-libinput-backend.service gives the following message multiple times that seems to be unrelated:
~~~
jan 15 17:24:59 laptop swayosd-libinput-backend[8257]: See https://wayland.freedesktop.org/libinput/doc/1.24.0/touchpad-jumping-cursors.html for details
jan 15 17:24:59 laptop swayosd-libinput-backend[8257]: libinput error: event4  - MSFT0001:00 04F3:31BD Touchpad: kernel bug: Touch jump detected and discarded. 
~~~

Thanks for the help!

(Edit for spelling)

**Comment by ErikReider** [comment]
Is this still an issue? Closing in the mean time
