### ISSUE TITLE
Port to GTK4 ?

### ISSUE THREAD

**Issue by werdahias** [ErikReider/SwayOSD#75]
Thanks for your work. gtk4-layershell is already available. No idea how much effort a port from GTK3 to 4 is in this scope, but that would be nice to have imo. I might look into this.

**Comment by Ferdi265** [comment]
Just looked into this a bit. The main issue is likely that `gtk4-rs` removed the `Sender` and `Receiver` channels that are extensively used throughout SwayOSD. [The issue that suggested the removal](https://github.com/gtk-rs/gtk-rs-core/issues/1213) seems to note that async should be used instead. This looks like it's a nontrivial change though.

**Comment by werdahias** [comment]
Thanks for looking into this ! Note that gtk3-rs is EOL and archived upstream so a GTK4 port would make sense sooner or later
