### ISSUE TITLE
Volume limit

### ISSUE THREAD

**Issue by averyanalex** [ErikReider/SwayOSD#8]
Maybe limit max volume to 100% or 150% (and add config option)?

**Comment by ErikReider** [comment]
This doesn't have any config. I'd need to add one then when I have time :)

In the mean time, you can always just not run the swayosd volume command if the volume is above 150

**Comment by averyanalex** [comment]
> This doesn't have any config. I'd need to add one then when I have time :)
> 
> In the mean time, you can always just not run the swayosd volume command if the volume is above 150

As config I mean cmd option "--volume-limit 150"

**Comment by Teddy-Kun** [comment]
Has there been any work done on this? If not I would create a PR as I also want this feature. If you haven't started work in this, how would you like it to be added: config file, command line argument or both (the latter overwriting the former)?

**Comment by ErikReider** [comment]
> Has there been any work done on this? If not I would create a PR as I also want this feature. If you haven't started work in this, how would you like it to be added: config file, command line argument or both (the latter overwriting the former)?

I've had a lot to do the past weeks so haven't had any time 😅. Go for it! A cmd line arg would be the best :)

**Comment by averyanalex** [comment]
> 

No, I didn't do any work.

I think it will be better to add max volume agrument to volume raise command.

Also maybe GNOME-like visual, i.e. red color when volume > 100.

Sorry for my bad English:)

**Comment by ErikReider** [comment]
> Should the argument be there when starting swayosd or when calling --output-volume raise?

Hmm. One way would be to add a options struct (for future options) to `SwayOSDApplication` and initialize it with 100 as the limit? Any other ideas?

**Comment by Teddy-Kun** [comment]
I'll open a PR soon, then you'll see how I have done it. Need to fix the last bug though...
