### ISSUE TITLE
how do i run this?

### ISSUE THREAD

**Issue by szymon420699** [ErikReider/SwayOSD#81]
starting the systemd service doesnt work nor starting the server please help thanks

**Comment by mike-lloyd03** [comment]
Might be helpful to include the error messages you're getting when trying to start the server.

**Comment by jamesponddotco** [comment]
Same problem here. When trying to run `swayosd-client --output-volume raise`, for example, I get:

```
Could not connect to SwayOSD Server with error: org.freedesktop.DBus.Error.ServiceUnknown: The name org.erikreider.swayosd-server was not provided by any .service files
```

Running `swayosd-client` with any commands or arguments result in the same error.

`systemctl status swayosd-libinput-backend.service` shows the service running and no error messages are displayed in the journal.

I'm running openSUSE Tumbleweed, if that matters.

**Comment by jamesponddotco** [comment]
Found the problem, I feel stupid. Forgot to add `exec swayosd-server` to sway's config file :facepalm:

**Comment by SaadAhmedGit** [comment]
For anyone having the same problem, using `exec_always` instead of `exec` in `exec swayosd-server` did the job for me
