### ISSUE TITLE
Swayosd stopped showing the correct icon after update

### ISSUE THREAD

**Issue by abinlatheef** [ErikReider/SwayOSD#84]
![image](https://github.com/ErikReider/SwayOSD/assets/63762448/e9c31936-e4bd-4201-9e9a-49ad659a98fb)

It now shows a box for every operation. No I did not delete or add new icon or font packs.

**Comment by shvedes** [comment]
> ![image](https://private-user-images.githubusercontent.com/63762448/337867350-e9c31936-e4bd-4201-9e9a-49ad659a98fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDAyNDcsIm5iZiI6MTcyMzU5OTk0NywicGF0aCI6Ii82Mzc2MjQ0OC8zMzc4NjczNTAtZTljMzE5MzYtZTRiZC00MjAxLTllOWEtNDlhZDY1OWE5OGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAxNDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDRkMzI5ZjMxMGE2Nzk5NmQ3YWNkNGQxMTNmYmYyNGJlMDA2MTIwMzc4NDkzYmJjNmFjNzc2MDk5Y2JmMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qR4QN9fsNIKBnoO3bP8lZ7LZBtHS6X8g8aF7cB_oygg)
> 
> It now shows a box for every operation. No I did not delete or add new icon or font packs.

rm -rf $HOME/.local/share/icon/hicolor

**Comment by ErikReider** [comment]
This is a Adwaita icon theme issue where they removed legacy icons
