### ISSUE TITLE
SwayOSD in light mode despite Adwaita Dark as preference

### ISSUE THREAD

**Issue by lollar1337** [ErikReider/SwayOSD#92]
Even when setting Adwaita Dark and prefer dark swayosd stays in light mode. Any idea how to fix that?

**Comment by checkinindza** [comment]
Same issue here, using SwayOSD on Hyprland.

**Comment by checkinindza** [comment]
In my case the issue was I hadn't installed `gnome-themes-extra` package. After installing that, SwayOSD was in dark mode.

**Comment by ralmachado** [comment]
In my case, SwayOSD seems to ignore the color-scheme setting, and only switches to the dark background when gtk-theme is set to `Adwaita-dark`.

I'm on Fedora 40, with SwayOSD built on the latest commit (d304967).

**Comment by ErikReider** [comment]
SwayOSD is using CSS variables provided by your GTK3 theme. Nothing that I can do about it
