### ISSUE TITLE
Mic mute-toggle does not toggle the led on the keyboard

### ISSUE THREAD

**Issue by TurtleMeds** [ErikReider/SwayOSD#99]
When I bind the mic mute button to `swayosd --input-volume mute-toggle` the OSD shows that it is working, but the led on the keyboard is always on.
Output of `ls /sys/class/leds`:
```
enp2s0-0::lan  enp2s0-2::lan	 input21::compose  input21::misc  input21::numlock	input21::sleep	 input4::capslock  input4::scrolllock	platform::mute	     tpacpi::power    tpacpi::thinkvantage
enp2s0-1::lan  input21::capslock  input21::kana     input21::mute  input21::scrolllock	input21::suspend  input4::numlock   platform::micmute	tpacpi::lid_logo_dot  tpacpi::standby
```

Please ask if you need any more clarification.

OS/Distro: Arch linux 
wm: Hyprland
Laptop: ThinkPad E16

**Comment by ErikReider** [comment]
Nothing that I can do about it, I'm only using the pulse API provided by https://crates.io/crates/pulsectl-rs

**Comment by gabrielrinaldi** [comment]
Can't you add the same support you have for the capslock led to pass the led for mude and mic mute?
